# Generated by Django 3.1.1 on 2020-12-10 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_currency',
        ),
    ]
