# Generated by Django 3.1.1 on 2020-12-11 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20201209_2227'),
        ('payments', '0003_auto_20201211_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, limit_choices_to={'default_address': True}, on_delete=django.db.models.deletion.CASCADE, to='accounts.useraddress'),
        ),
    ]
