# Generated by Django 3.1.1 on 2020-12-09 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201005_2332'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAddress',
        ),
    ]
