# Generated by Django 3.1.1 on 2020-12-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_useraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='default_address',
            field=models.BooleanField(default=False),
        ),
    ]
