# Generated by Django 3.1.1 on 2020-12-09 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_useraddress_default_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='default_address',
        ),
    ]
