# Generated by Django 3.1.1 on 2020-12-25 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20201211_2039'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
