# Generated by Django 3.1.1 on 2021-01-10 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0010_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='default_address',
            field=models.BooleanField(default=False, help_text='Mark this for future items to be delivered at this address'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='full_name',
            field=models.CharField(help_text='Full Name of the user', max_length=50),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='landmark',
            field=models.CharField(blank=True, help_text='Landmark e.g. Paras Hospital, DPS School', max_length=30),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='phone_no',
            field=models.CharField(help_text='Phone Number', max_length=10),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='pincode',
            field=models.CharField(help_text='Address Pincode', max_length=6),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='user',
            field=models.ForeignKey(help_text='Added by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
