# Generated by Django 3.1.1 on 2020-12-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20201205_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_value',
            field=models.FloatField(default=0),
        ),
    ]
