# Generated by Django 3.1.1 on 2020-12-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_cart_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
