# Generated by Django 3.1.1 on 2020-12-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_remove_cart_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='delivered_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
