# Generated by Django 3.1.1 on 2020-12-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_cart_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='ordered_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
