# Generated by Django 3.1.1 on 2020-12-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_cart_delivery_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='shipped',
            field=models.BooleanField(default=False, help_text='Mark if cart products are shipped'),
        ),
    ]
