# Generated by Django 3.1.1 on 2020-12-25 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_cart_shipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='shipped_on',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
