# Generated by Django 3.1.1 on 2020-12-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_cart_shipped_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='shipped_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
