# Generated by Django 3.1.1 on 2021-01-10 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0020_auto_20210106_2208'),
        ('cart', '0013_auto_20201225_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_value',
            field=models.FloatField(default=0, help_text='Cart price'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='completed',
            field=models.BooleanField(default=False, help_text='Mark this is user paid for this cart'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='delivered',
            field=models.BooleanField(default=False, help_text='Mark if cart products are Delivered'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='delivered_on',
            field=models.DateField(blank=True, help_text='Cart products delivered on', null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='ordered_on',
            field=models.DateTimeField(blank=True, help_text='Cart Ordered by user on', null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(help_text='cart user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='price',
            field=models.FloatField(help_text='Product price', null=True),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='product',
            field=models.ForeignKey(help_text='Product name', on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='quantity',
            field=models.IntegerField(default=1, help_text='Product quantity'),
        ),
    ]
