# Generated by Django 3.1.1 on 2020-12-04 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20201204_1948'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
