# Generated by Django 3.1.1 on 2020-12-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20201206_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='highlight',
            field=models.BooleanField(default=False, help_text='To display product on homepage'),
        ),
    ]
