# Generated by Django 3.1.1 on 2020-12-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_highlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buy_limit',
            field=models.IntegerField(default=4),
        ),
    ]
