# Generated by Django 3.1.1 on 2021-01-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20210106_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, help_text='Without discount price. Leave Blank if no discount', null=True),
        ),
    ]
