# Generated by Django 3.1.1 on 2021-01-06 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20210106_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text='Product will appear in selected category', null=True, on_delete=django.db.models.deletion.RESTRICT, to='products.category'),
        ),
    ]
